services:
  app:
    build:
      context: .
      target: production
      args:
        - PUBLIC_PB_HOST_PROD=${PUBLIC_PB_HOST_PROD}
        - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
        - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST_PROD}
    depends_on:
      pb:
        condition: service_healthy

  pb:
    build:
      context: .
      dockerfile: pocketbase/Dockerfile
    environment:
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_TEST_ADMIN_EMAIL=${PB_TEST_ADMIN_EMAIL}
      - PB_TEST_ADMIN_PASSWORD=${PB_TEST_ADMIN_PASSWORD}
    volumes:
      - "/app/pb_data"
      - "/app/pb_migrations"
    restart: unless-stopped
    healthcheck:
      test: wget --tries=1 --spider http://127.0.0.1:8081/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 300s

  tools:
    build:
      context: .
      dockerfile: tools.Dockerfile
    working_dir: /app
    environment:
      - PUBLIC_PB_HOST_PROD=${PUBLIC_PB_HOST_PROD}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
    volumes:
      - ./:/app
      - tools_node_modules:/app/node_modules

volumes:
  tools_node_modules:
