services:
  pb:
    build: ./pocketbase
    ports:
      - "8080:8080"
    environment:
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_TEST_ADMIN_EMAIL=${PB_TEST_ADMIN_EMAIL}
      - PB_TEST_ADMIN_PASSWORD=${PB_TEST_ADMIN_PASSWORD}
      - POCKETBASE_ENVIRONMENT=${COOLIFY_BRANCH_SLUG:-dev}
    volumes:
      - pbdata:/app/pb_data
      - svelte_kit_data:/app/.svelte-kit      
    depends_on:
      pb:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pb-${COOLIFY_BRANCH_SLUG:-dev}.rule=Host(`pb-${COOLIFY_BRANCH_SLUG:-dev}.kaffediem-backend.asvg.codes`)"
      - "traefik.http.routers.pb-${COOLIFY_BRANCH_SLUG:-dev}.entrypoints=web"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      target: development
      args:
        - PUBLIC_PB_HOST_PROD=${PUBLIC_PB_HOST_PROD}
        - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
        - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST:-https://pb-${COOLIFY_BRANCH_SLUG:-dev}.kaffediem-backend.asvg.codes}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - "node_modules/"
            - "**/*.test.ts"
            - "**/*.spec.ts"
        - action: sync
          path: ./static
          target: /app/static

        - action: sync+restart
          path: ./vite.config.ts
          target: /app/vite.config.ts
        - action: sync+restart
          path: ./svelte.config.js
          target: /app/svelte.config.js
        - action: sync+restart
          path: ./tsconfig.json
          target: /app/tsconfig.json
        - action: sync+restart
          path: ./.env
          target: /app/.env

        - action: rebuild
          path: package.json

volumes:
  svelte_kit_data:
  pbdata:
    name: "pbdata-${COOLIFY_BRANCH_SLUG:-dev}"
