services:
  app:
    build:
      context: .
      target: production
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
        - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS}
  tools:
    build:
      context: .
      dockerfile: tools.Dockerfile
    working_dir: /app
    environment:
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS}
    volumes:
      - ./:/app
      - tools_node_modules:/app/node_modules

volumes:
  tools_node_modules:
