services:
  app:
    ports:
      - "3000:3000"
    build:
      context: .
      target: production
      args:
        - PUBLIC_PB_HOST_PROD=${PUBLIC_PB_HOST_PROD}
        - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
        - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST_PROD}
    depends_on:
      pb:
        condition: service_healthy 

  pb:
    build: ./pocketbase
    ports:
      - "8081:8081"
    labels:
      - "traefik.http.services.pb.loadbalancer.server.port=8081"
    environment:
      - PUBLIC_PB_HOST=${PUBLIC_PB_HOST}
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_TEST_ADMIN_EMAIL=${PB_TEST_ADMIN_EMAIL}
      - PB_TEST_ADMIN_PASSWORD=${PB_TEST_ADMIN_PASSWORD}
    volumes:
      - "./pocketbase/pb_data:/app/pb_data"
      - "./pocketbase/pb_migrations:/app/pb_migrations"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
