services:
  backend:
    build:
      context: ./kaffebase
      dockerfile: Dockerfile
    working_dir: /app
    command: mix phx.server
    volumes:
      - backend_deps:/app/deps
      - backend_build:/app/_build
    ports:
      - "4000:4000"

  app:
    build:
      context: .
      target: production
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
        - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    depends_on:
      backend:
        condition: service_started

  tools:
    build:
      context: .
      dockerfile: tools.Dockerfile
    working_dir: /app
    environment:
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    volumes:
      - ./:/app
      - tools_node_modules:/app/node_modules

volumes:
  tools_node_modules:
  backend_deps:
  backend_build:
