services:
  backend:
    build:
      context: ./kaffebase
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - backend_deps:/app/deps
      - backend_build:/app/_build
      - backend_data:/app/data
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
        - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"

  tools:
    build:
      context: .
      dockerfile: scripts/tools.Dockerfile
    working_dir: /app/frontend
    environment:
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL:-http://backend:4000}
      - PUBLIC_BACKEND_WS=${PUBLIC_BACKEND_WS:-ws://backend:4000/socket}
    volumes:
      - ./:/app
      - tools_node_modules:/app/frontend/node_modules

volumes:
  tools_node_modules:
  backend_deps:
  backend_build:
  backend_data:
