import Config

# Configure your database
config :kaffebase, Kaffebase.Repo,
  database: Path.expand("../kaffebase_dev.db", Path.dirname(__ENV__.file)),
  pool_size: 1,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :kaffebase, KaffebaseWeb.Endpoint,
  # Binding to all interfaces to allow access from Docker containers and host
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "NLFepuwpLJpLxUpaYULQJpd1c8FjP+qoGHAyt70cE7GySShFuKFl3+FFFX+FuyNn",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kaffebase, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:kaffebase, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kaffebase, KaffebaseWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/kaffebase_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kaffebase, dev_routes: true

# Include timestamps and metadata in development logs for better debugging
config :logger, :console, format: "[$time] [$level] $message\n", metadata: [:request_id]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
