name: Bug
description: Noe virker ikke slik det skal
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: "Jeg har:"
      description:
      options:
        - label: Sett etter lignende issues
          required: true
  - type: textarea
    attributes:
      label: Beskriv problemet
      description: Hvordan reproduseres feilen?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: På hvilke nettlesere skjer problemet?
      multiple: true
      options:
        - Firefox
        - Chromium
        - Safari
  - type: textarea
    attributes:
      label: Relevante logs
      description: Lim inn logs fra konsollen
      render: shell
