name: Forbedring
description: Forslag til ny funksjonalitet eller forbedrelse
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: "Jeg har:"
      description:
      options:
        - label: Sett etter lignende issues
          required: true
  - type: textarea
    attributes:
      label: Beskriv forslaget
      description: Gjerne gi forslag til hvordan det kan implementeres
    validations:
      required: true
