app = "kaffediem-kaffebase"
primary_region = "arn"


[env]
  PHX_SERVER = "true"
  PHX_HOST = "https://kaffediem-kaffebase.fly.dev"
  PORT = "4000"
  DATABASE_PATH = "/app/data/kaffebase_prod.db"
  PHX_ALLOWED_ORIGINS = "https://kaffebase.okpl.us,https://kaffediem.okpl.us,https://kaffediem-kaffebase.fly.dev"

[deploy]
  release_command = "/app/bin/kaffebase eval \"Kaffebase.Release.migrate\""

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    soft_limit = 80
    hard_limit = 100

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1024mb"

[[mounts]]
  source = "kaffebase_data"
  destination = "/app/data"
  initial_size = "1GB"
